### ISSUE TITLE
Bottom Retrieve page buttons - update globally

### ISSUE THREAD

**Issue by bartmika** [over55/overfiftyfive-django#62] opened 2018-04-28 04:01 UTC
![screen shot 2018-04-27 at 11 59 44 pm](https://user-images.githubusercontent.com/5767602/39391788-28b65e3a-4a77-11e8-985f-71f70df8ddc0.png)

Every retrieve page needs the page fixed so the comments are looking better.

@rodolfomartinez FYI

**Comment by rodolfomartinez** [comment] 2018-05-04 02:45
Duplicate of #82

**Closed by rodolfomartinez** 2018-05-04 02:45 UTC
Labels: bug
